from storage import load_queue

messages = (
    """More people than you realize are neurodivergent, that many of them live successful and fulfilling lives."""
    """Having a name for how your brain works makes it so much easier to make life easier for yourself.""",
    """oh...that's why that happened... (when thinking about my entire life history!)""",
    """The ways you thrive probably looks different than for most people around you.""",
    """Be patient with yourself and get more familiar with what these ways are, and soon enough you'll learn to recognize how your superpowers can help everyone and especially yourself. """,
    """Learn and get used to accepting help from others. We don't need to do any of this on our own.""",
    """(Recieving a dianosis) caused me to reflect on my past and realize why things were so difficult for me when they came easily to others. """,
    """It gave me permission to accept myself and try to build a life that is better suited for me, even when it does not meet the expectations of others. """,
    """You are absolutely fine the way you are, and we still love you and will be there when you need us the most. """,
    """I stopped trying to fight my brain and started trying to create systems that could work with it.""",
    """ I wish I had learned about and accepted this sooner instead of blaming myself all the time.""",
    """Diversity is beautiful. Difference should be celebrated.""",
    """Research shows diverse teams make for better-performing companies. You are valuable, just as you are""",
    """There's nothing wrong with being neurodivergent. Sometimes it can be difficult in a world made for one type of thinker, but equally the ability to think differently can be fantastic.""",
    """You are not disabled. You are amazing, and unique, and so resilient, and have boundless capabilities.""",
    """Find and leverage your SUPERPOWERS, while managing areas of growth.""",
    """Neurodivergence is rooted in physiological factors that is outside of personal control, there is no more "blame" involved than having hypothyroidism or seizures.""",
    """You are not broken of disabled.  You merely experience the world through a unique lens.""",
    """Take a breath, take your time and take care of yourself. """,
    """If something isn't working for you, if an aspect of life isn't functional - it is ok to do it however you need to in order for it to work well for you. """,
    """You are a valuable and unique human being and it is OK to structure your home and work in ways that set you up for success! """,
    """It is OK and normal to try many things before finding one that works for you.""",
    """Don't give up, and feel the success in understanding what does - and doesn't - serve your best interests.""",
    """Different does not equal bad or less. Different makes you valuable.""",
    """Some people might not understand why it's so important for to seek diagnosis or treatment, especially if you've appeared "high functioning" to them for most of your life. Unless it's important to you that they understand, they don't have to. """,
    """Your concerns are legitimate - acknowledging that something isn't quite right, seeking help, and being vulnerable is something to always be proud of.""",
    """Armed with this knowledge you are so much better equipped to deal with Neurotypicals""",
    """There are so many of us :) Everything will be ok . It’s ok to do things your own way""",
    """(Getting diagnosed) was like a huge burden fell off my shoulders!""",
    """Knowing how my brain is wired and that it’s not a long line of personal failures lead to self kindness for me.""",
    """Finding myself in a circle of people who talked openly about neurodiversity & learning that I have it was a relief, in a way.""",
    """The process of diagnosis will be hard, but the growth you gain from the process of self discovery will be the greatest part of your life thus far. Stay on your path. :) """,
    """Don't mask to the doctors. It can be hard to stop and embarrassing to answer their questions honestly, but you want to have an accurate diagnosis if this is the route you're pursuing! They're not going to judge you for the things they're trying to help you with.""",
    """Just because you think you can function without knowing or addressing it, doesn't mean that it's wrong to get help!""",
    """Getting help can make things easier, even if your life isn't terribly difficult because of your neurodivergency.""",
    """There's plenty help for everyone available, so you getting help doesn't mean that others who are "worse" off can't get help.""",
    """I burst into tears of relief when I got my diagnosis. I wasn’t lazy; my brain was different.""",
    """It’s OK that you need time to figure out how to do something in a way that works for you.""",
    """It’s OK that some days, not much gets done because you don’t know where to start.""",
    """It’s OK to lower the bar you’ve set for yourself for whatever reason.""",
    """Don’t beat yourself up over not consistently managing as much as a neurotypical person, you don’t have the same tool box as they do. Yours isn’t worse, it’s just different - and that’s OK.""",
    """"GET DIAGNOSED! Your insurance will probably cover your psychiatric appointments and you may not need a referral.""",
    """Find a good provider - you don’t have to stick with the first one you find if they aren’t a good fit for you.""",
    """(For my moderate ADHD) You don't have to take medication or change your life drastically if you don't want""",
    """Just knowing is helpful in wrangling your behaviors under control!""",
    """Many times it is not easy to handle as the outer world has not been designed for neurodivergent people. So, it is totally ok to seek guidance, support, and medication.""",
    """I wish there was not this much stigma around medication for neurodivergent.""",
    """Saying everything is “imposter syndrome” kept me undiagnosed for way longer than necessary. Some people are actually struggling and it’s NOT normal.""",
    """You are still the same person you were before you got your diagnosis. Nothing has changed about that.""",
    """Hopefully it can help you better understand how your own brain works and how that might be different from others.""",
    """Be proud of who you are!""",
)

queue = load_queue("31daysofndqueue")

for index_, message in enumerate(messages, start=1):
    queue.send_message(f"{index_} - {message}", time_to_live=-1)
